#!/bin/bash

APP_PATH="$(cd "$(dirname "$0")/.." && pwd)"
RESOURCES_PATH="$APP_PATH/Resources"

osascript <<EOF
tell application "Terminal"
    activate
    do script "cd '$RESOURCES_PATH' && chmod +x '一键安装.sh' && bash '一键安装.sh'"
end tell
EOF