#!/bin/bash

APP_PATH="$(cd "$(dirname "$0")/.." && pwd)"
RESOURCES_PATH="$APP_PATH/Resources"

osascript <<EOF
tell application "Terminal"
    activate
    do script "cd '$RESOURCES_PATH' && python3 launcher.py"
end tell

delay 0.1

tell application "Terminal"
    set miniaturized of every window to true
end tell
EOF